from django.urls import path
from leakscope_app import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('home/', views.index, name='home'),
    path('search/', views.keyword, name='search'),
    path('search/<str:type>', views.search, name='search'),
    path('keyword/', views.keyword, name='keyword'),
    path('keyword/search', views.keyword_search_results, name='keyword_search_results'),
    path('search/<str:type>/results', views.search_results, name='search_results'),
    path('search/<str:type>/browse/', views.browse, name='browse'),
    path('database/', views.database, name='database'),
    # Monitor routes removed
    path('stats/<str:type>', views.stats, name='stats'),
    path('stats_db/<str:type>', views.stats_db, name='stats_db'),
    path('get-task-info/', views.get_task_info, name='get_task_info'),
    path('hide/<str:type>/<str:ip>', views.hide, name='hide'),
    path('amazon_buckets/', views.amazonbuckets, name="amazonbuckets"),
    path('amazon_buckets/brute/', views.bruteforce_bucket, name="bruteforce_bucket"),
    path('javascript/', views.js, name="javascript"),
    path('javascript/file', views.js_file, name="javascript_file"),
    path('github/', views.github, name="github"),
    path('github/repo', views.github_repo, name="github_repo"),
    path('export/', views.export_results, name="export_results"),
    path('export-import/', views.export_import, name="export_import"),
    path('custom-queries/', views.custom_queries, name="custom_queries"),
    path('custom-queries/list', views.custom_query_list, name="custom_query_list"),
    path('custom-queries/save', views.custom_query_save, name="custom_query_save"),
    path('custom-queries/delete', views.custom_query_delete, name="custom_query_delete"),
    path('custom-queries/run', views.custom_query_run, name="custom_query_run"),
    path('preview/', views.preview_page, name="preview_page"),
    path('preview/targets', views.preview_targets, name="preview_targets"),
    path('preview/start', views.preview_start, name="preview_start"),
    path('export/start', views.export_start, name="export_start"),
    path('export/download/<str:token>', views.export_download, name="export_download"),
    path('explore/', views.explore_page, name="explore_page"),
    path('explore/start', views.explore_start, name="explore_start"),
    path('explore/next', views.explore_next, name="explore_next"),
]
